version: "3"
## About database
services:
  db:
    build: ./db
    image: mysql/mysql-server
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test_db"
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "user"
    ports:
      - "33062:33062"
    volumes: 
      - ./db:/db
    environment: 
      PORT : 3006
    ## https://www.grottedubarbu.fr/docker-healthcheck/
    healthcheck:
      test: curl --fail -s http://localhost:3306/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

## About the web project
  web:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    environment: 
      PORT : 5000
    volumes: 
      -./app:/app
    ## https://www.grottedubarbu.fr/docker-healthcheck/
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5